// <auto-generated />
using System;
using HelpEmpowermentApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpEmpowermentApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203012900_addquestion")]
    partial class addquestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpEmpowermentApi.Models.AppLookupDetail", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LookupHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LookupNameAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("LookupHeaderId", "IsActive");

                    b.HasIndex("LookupHeaderId", "LookupValue");

                    b.ToTable("AppLookupD");

                    b.HasData(
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "مبتدئ",
                            LookupNameEn = "Beginner",
                            LookupValue = "BEGINNER",
                            OrderNo = 1
                        },
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "متوسط",
                            LookupNameEn = "Intermediate",
                            LookupValue = "INTERMEDIATE",
                            OrderNo = 2
                        },
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "متقدم",
                            LookupNameEn = "Advanced",
                            LookupValue = "ADVANCED",
                            OrderNo = 3
                        },
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "خبير",
                            LookupNameEn = "Expert",
                            LookupValue = "EXPERT",
                            OrderNo = 4
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "البرمجة",
                            LookupNameEn = "Programming",
                            LookupValue = "PROGRAMMING",
                            OrderNo = 1
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الطب",
                            LookupNameEn = "Medical",
                            LookupValue = "MEDICAL",
                            OrderNo = 2
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "المالية",
                            LookupNameEn = "Finance",
                            LookupValue = "FINANCE",
                            OrderNo = 3
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الهندسة",
                            LookupNameEn = "Engineering",
                            LookupValue = "ENGINEERING",
                            OrderNo = 4
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الأعمال",
                            LookupNameEn = "Business",
                            LookupValue = "BUSINESS",
                            OrderNo = 5
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "التصميم",
                            LookupNameEn = "Design",
                            LookupValue = "DESIGN",
                            OrderNo = 6
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "التسويق",
                            LookupNameEn = "Marketing",
                            LookupValue = "MARKETING",
                            OrderNo = 7
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "اللغة",
                            LookupNameEn = "Language",
                            LookupValue = "LANGUAGE",
                            OrderNo = 8
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222209"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "علم البيانات",
                            LookupNameEn = "Data Science",
                            LookupValue = "DATA_SCIENCE",
                            OrderNo = 9
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222210"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الأمن السيبراني",
                            LookupNameEn = "Cybersecurity",
                            LookupValue = "CYBERSECURITY",
                            OrderNo = 10
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LookupNameAr = "اختيار من متعدد",
                            LookupNameEn = "Multiple Choice Question",
                            LookupValue = "MCQ",
                            OrderNo = 1
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LookupNameAr = "صح أو خطأ",
                            LookupNameEn = "True/False",
                            LookupValue = "TRUE_FALSE",
                            OrderNo = 2
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333306"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LookupNameAr = "مطابقة",
                            LookupNameEn = "Matching",
                            LookupValue = "MATCHING",
                            OrderNo = 6
                        });
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.AppLookupHeader", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LookupNameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LookupCode")
                        .IsUnique();

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.ToTable("AppLookupH");

                    b.HasData(
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupCode = "COURSE_LEVEL",
                            LookupNameAr = "مستوى الدورة",
                            LookupNameEn = "Course Level"
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupCode = "COURSE_CATEGORY",
                            LookupNameAr = "فئة الدورة",
                            LookupNameEn = "Course Category"
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupCode = "QUESTION_TYPE",
                            LookupNameAr = "نوع السؤال",
                            LookupNameEn = "Question Type"
                        });
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.Course", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseCategoryLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("text");

                    b.Property<Guid?>("CourseLevelLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("HeaderOne")
                        .HasColumnType("text");

                    b.Property<string>("HeaderTwo")
                        .HasColumnType("text");

                    b.Property<Guid?>("InstructorOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseCategoryLookupId");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.HasIndex("CourseLevelLookupId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InstructorOid");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseAnswer", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("OrderNo");

                    b.HasIndex("QuestionId");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsCorrect");

                    b.ToTable("course_answers");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseContent", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContentTypeLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOutlineOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("ContentTypeLookupId");

                    b.HasIndex("CourseOutlineOid");

                    b.HasIndex("IsDeleted");

                    b.ToTable("course_contents");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseFeature", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeatureDescription")
                        .HasColumnType("text");

                    b.Property<string>("FeatureHeader")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("IsDeleted");

                    b.ToTable("course_features");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseInstructor", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BioAr")
                        .HasColumnType("text");

                    b.Property<string>("BioEn")
                        .HasColumnType("text");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("HeaderAr")
                        .HasColumnType("text");

                    b.Property<string>("HeaderEn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("IsDeleted");

                    b.ToTable("course_instructors");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseLiveSession", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxNumberReservation")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfReservations")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("Date");

                    b.HasIndex("IsDeleted", "Active");

                    b.ToTable("course_Live_Session");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseLiveSessionStudent", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("StudentOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentOid");

                    b.HasIndex("CourseOid", "StudentOid")
                        .IsUnique();

                    b.ToTable("course_Live_Session_Studient");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseOutline", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("TitleAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("IsDeleted");

                    b.ToTable("course_outline");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseQuestion", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CorrectChoiceOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursesMasterExamOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<bool>("Question")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionScore")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuestionTypeLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CorrectChoiceOid");

                    b.HasIndex("CoursesMasterExamOid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("OrderNo");

                    b.HasIndex("QuestionTypeLookupId");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("course_questions");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseTargetAudience", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("IsDeleted");

                    b.ToTable("course_target_audience");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseVideo", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VideoTypeLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Oid");

                    b.HasIndex("CourseOid");

                    b.HasIndex("VideoTypeLookupId");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("course_videos");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseVideoAttachment", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseVideoOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FileTypeLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CourseVideoOid");

                    b.HasIndex("FileTypeLookupId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("course_video_attachments");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CoursesMasterExam", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseCategoryLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseLevelLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("PassPercent")
                        .HasColumnType("int");

                    b.Property<bool>("ShuffleAnswers")
                        .HasColumnType("bit");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseCategoryLookupId");

                    b.HasIndex("CourseLevelLookupId");

                    b.HasIndex("CourseOid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("courses_Master_Exam");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.Student", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Oid");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("students");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.StudentExam", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<Guid>("CoursesMasterExamOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExamStatusLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<int?>("ObtainedScore")
                        .HasColumnType("int");

                    b.Property<int?>("PassPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CoursesMasterExamOid");

                    b.HasIndex("ExamStatusLookupId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StudentOid");

                    b.HasIndex("StudentOid", "CoursesMasterExamOid");

                    b.ToTable("student_exams");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.StudentExamQuestion", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ObtainedScore")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QuestionScore")
                        .HasColumnType("int");

                    b.Property<Guid?>("SelectedAnswerOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentExamOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("QuestionOid");

                    b.HasIndex("SelectedAnswerOid");

                    b.HasIndex("StudentExamOid");

                    b.ToTable("student_exam_questions");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.User", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("RoleLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StatusLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Oid");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RoleLookupId");

                    b.HasIndex("StatusLookupId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("users");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.AppLookupDetail", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.AppLookupHeader", "LookupHeader")
                        .WithMany("LookupDetails")
                        .HasForeignKey("LookupHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LookupHeader");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.Course", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "CourseCategoryLookup")
                        .WithMany()
                        .HasForeignKey("CourseCategoryLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "CourseLevelLookup")
                        .WithMany()
                        .HasForeignKey("CourseLevelLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.User", "Instructor")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("InstructorOid");

                    b.Navigation("CourseCategoryLookup");

                    b.Navigation("CourseLevelLookup");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseAnswer", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.CourseQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseContent", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "ContentTypeLookup")
                        .WithMany()
                        .HasForeignKey("ContentTypeLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.CourseOutline", "CourseOutline")
                        .WithMany("Contents")
                        .HasForeignKey("CourseOutlineOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentTypeLookup");

                    b.Navigation("CourseOutline");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseFeature", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("Features")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseInstructor", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseLiveSession", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("LiveSessions")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseLiveSessionStudent", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.CourseLiveSession", "LiveSession")
                        .WithMany("SessionStudents")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpEmpowermentApi.Models.Student", "Student")
                        .WithMany("LiveSessionEnrollments")
                        .HasForeignKey("StudentOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LiveSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseOutline", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("Outlines")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseQuestion", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.CourseQuestion", "CorrectChoice")
                        .WithMany()
                        .HasForeignKey("CorrectChoiceOid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.CoursesMasterExam", "MasterExam")
                        .WithMany("Questions")
                        .HasForeignKey("CoursesMasterExamOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "QuestionTypeLookup")
                        .WithMany()
                        .HasForeignKey("QuestionTypeLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorrectChoice");

                    b.Navigation("MasterExam");

                    b.Navigation("QuestionTypeLookup");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseTargetAudience", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("TargetAudiences")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseVideo", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("Videos")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "VideoTypeLookup")
                        .WithMany()
                        .HasForeignKey("VideoTypeLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Course");

                    b.Navigation("VideoTypeLookup");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseVideoAttachment", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.CourseVideo", "CourseVideo")
                        .WithMany("Attachments")
                        .HasForeignKey("CourseVideoOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "FileTypeLookup")
                        .WithMany()
                        .HasForeignKey("FileTypeLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CourseVideo");

                    b.Navigation("FileTypeLookup");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CoursesMasterExam", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "CourseCategoryLookup")
                        .WithMany()
                        .HasForeignKey("CourseCategoryLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "CourseLevelLookup")
                        .WithMany()
                        .HasForeignKey("CourseLevelLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.Course", "Course")
                        .WithMany("MasterExams")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseCategoryLookup");

                    b.Navigation("CourseLevelLookup");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.StudentExam", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.CoursesMasterExam", "MasterExam")
                        .WithMany()
                        .HasForeignKey("CoursesMasterExamOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "ExamStatusLookup")
                        .WithMany()
                        .HasForeignKey("ExamStatusLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.Student", "Student")
                        .WithMany("StudentExams")
                        .HasForeignKey("StudentOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamStatusLookup");

                    b.Navigation("MasterExam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.StudentExamQuestion", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.CourseQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpEmpowermentApi.Models.CourseAnswer", "SelectedAnswer")
                        .WithMany()
                        .HasForeignKey("SelectedAnswerOid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.StudentExam", "StudentExam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("StudentExamOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedAnswer");

                    b.Navigation("StudentExam");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.User", b =>
                {
                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "RoleLookup")
                        .WithMany()
                        .HasForeignKey("RoleLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpEmpowermentApi.Models.AppLookupDetail", "StatusLookup")
                        .WithMany()
                        .HasForeignKey("StatusLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RoleLookup");

                    b.Navigation("StatusLookup");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.AppLookupHeader", b =>
                {
                    b.Navigation("LookupDetails");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.Course", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Instructors");

                    b.Navigation("LiveSessions");

                    b.Navigation("MasterExams");

                    b.Navigation("Outlines");

                    b.Navigation("TargetAudiences");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseLiveSession", b =>
                {
                    b.Navigation("SessionStudents");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseOutline", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CourseVideo", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.CoursesMasterExam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.Student", b =>
                {
                    b.Navigation("LiveSessionEnrollments");

                    b.Navigation("StudentExams");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.StudentExam", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("HelpEmpowermentApi.Models.User", b =>
                {
                    b.Navigation("InstructorCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
