// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StandardArticture.Data;

#nullable disable

namespace StandardArticture.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StandardArticture.Models.AppLookupDetail", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LookupHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LookupNameAr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupNameEn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("LookupHeaderId", "IsActive");

                    b.HasIndex("LookupHeaderId", "LookupValue");

                    b.ToTable("AppLookupD");

                    b.HasData(
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "مبتدئ",
                            LookupNameEn = "Beginner",
                            LookupValue = "BEGINNER",
                            OrderNo = 1
                        },
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "متوسط",
                            LookupNameEn = "Intermediate",
                            LookupValue = "INTERMEDIATE",
                            OrderNo = 2
                        },
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "متقدم",
                            LookupNameEn = "Advanced",
                            LookupValue = "ADVANCED",
                            OrderNo = 3
                        },
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            LookupNameAr = "خبير",
                            LookupNameEn = "Expert",
                            LookupValue = "EXPERT",
                            OrderNo = 4
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "البرمجة",
                            LookupNameEn = "Programming",
                            LookupValue = "PROGRAMMING",
                            OrderNo = 1
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الطب",
                            LookupNameEn = "Medical",
                            LookupValue = "MEDICAL",
                            OrderNo = 2
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "المالية",
                            LookupNameEn = "Finance",
                            LookupValue = "FINANCE",
                            OrderNo = 3
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الهندسة",
                            LookupNameEn = "Engineering",
                            LookupValue = "ENGINEERING",
                            OrderNo = 4
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الأعمال",
                            LookupNameEn = "Business",
                            LookupValue = "BUSINESS",
                            OrderNo = 5
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "التصميم",
                            LookupNameEn = "Design",
                            LookupValue = "DESIGN",
                            OrderNo = 6
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "التسويق",
                            LookupNameEn = "Marketing",
                            LookupValue = "MARKETING",
                            OrderNo = 7
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "اللغة",
                            LookupNameEn = "Language",
                            LookupValue = "LANGUAGE",
                            OrderNo = 8
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222209"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "علم البيانات",
                            LookupNameEn = "Data Science",
                            LookupValue = "DATA_SCIENCE",
                            OrderNo = 9
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222210"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            LookupNameAr = "الأمن السيبراني",
                            LookupNameEn = "Cybersecurity",
                            LookupValue = "CYBERSECURITY",
                            OrderNo = 10
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LookupNameAr = "اختيار من متعدد",
                            LookupNameEn = "Multiple Choice Question",
                            LookupValue = "MCQ",
                            OrderNo = 1
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LookupNameAr = "صح أو خطأ",
                            LookupNameEn = "True/False",
                            LookupValue = "TRUE_FALSE",
                            OrderNo = 2
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333306"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupHeaderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            LookupNameAr = "مطابقة",
                            LookupNameEn = "Matching",
                            LookupValue = "MATCHING",
                            OrderNo = 6
                        });
                });

            modelBuilder.Entity("StandardArticture.Models.AppLookupHeader", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LookupCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LookupNameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LookupNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Oid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LookupCode")
                        .IsUnique();

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.ToTable("AppLookupH");

                    b.HasData(
                        new
                        {
                            Oid = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupCode = "COURSE_LEVEL",
                            LookupNameAr = "مستوى الدورة",
                            LookupNameEn = "Course Level"
                        },
                        new
                        {
                            Oid = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupCode = "COURSE_CATEGORY",
                            LookupNameAr = "فئة الدورة",
                            LookupNameEn = "Course Category"
                        },
                        new
                        {
                            Oid = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            LookupCode = "QUESTION_TYPE",
                            LookupNameAr = "نوع السؤال",
                            LookupNameEn = "Question Type"
                        });
                });

            modelBuilder.Entity("StandardArticture.Models.Course", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseCategoryLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("text");

                    b.Property<Guid?>("CourseLevelLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseCategoryLookupId");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.HasIndex("CourseLevelLookupId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("StandardArticture.Models.CourseAnswer", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("OrderNo");

                    b.HasIndex("QuestionId");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsCorrect");

                    b.ToTable("course_answers");
                });

            modelBuilder.Entity("StandardArticture.Models.CourseQuestion", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CorrectChoiceOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoursesMasterExamOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<bool>("Question")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionScore")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuestionTypeLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CorrectChoiceOid");

                    b.HasIndex("CoursesMasterExamOid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("OrderNo");

                    b.HasIndex("QuestionTypeLookupId");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("course_questions");
                });

            modelBuilder.Entity("StandardArticture.Models.CoursesMasterExam", b =>
                {
                    b.Property<Guid>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseCategoryLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseLevelLookupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("CourseOid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Oid");

                    b.HasIndex("CourseCategoryLookupId");

                    b.HasIndex("CourseLevelLookupId");

                    b.HasIndex("CourseOid");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Oid");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("IsDeleted", "IsActive");

                    b.ToTable("courses_Master_Exam");
                });

            modelBuilder.Entity("StandardArticture.Models.AppLookupDetail", b =>
                {
                    b.HasOne("StandardArticture.Models.AppLookupHeader", "LookupHeader")
                        .WithMany("LookupDetails")
                        .HasForeignKey("LookupHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LookupHeader");
                });

            modelBuilder.Entity("StandardArticture.Models.Course", b =>
                {
                    b.HasOne("StandardArticture.Models.AppLookupDetail", "CourseCategoryLookup")
                        .WithMany()
                        .HasForeignKey("CourseCategoryLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandardArticture.Models.AppLookupDetail", "CourseLevelLookup")
                        .WithMany()
                        .HasForeignKey("CourseLevelLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CourseCategoryLookup");

                    b.Navigation("CourseLevelLookup");
                });

            modelBuilder.Entity("StandardArticture.Models.CourseAnswer", b =>
                {
                    b.HasOne("StandardArticture.Models.CourseQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("StandardArticture.Models.CourseQuestion", b =>
                {
                    b.HasOne("StandardArticture.Models.CourseQuestion", "CorrectChoice")
                        .WithMany()
                        .HasForeignKey("CorrectChoiceOid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandardArticture.Models.CoursesMasterExam", "MasterExam")
                        .WithMany("Questions")
                        .HasForeignKey("CoursesMasterExamOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StandardArticture.Models.AppLookupDetail", "QuestionTypeLookup")
                        .WithMany()
                        .HasForeignKey("QuestionTypeLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorrectChoice");

                    b.Navigation("MasterExam");

                    b.Navigation("QuestionTypeLookup");
                });

            modelBuilder.Entity("StandardArticture.Models.CoursesMasterExam", b =>
                {
                    b.HasOne("StandardArticture.Models.AppLookupDetail", "CourseCategoryLookup")
                        .WithMany()
                        .HasForeignKey("CourseCategoryLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandardArticture.Models.AppLookupDetail", "CourseLevelLookup")
                        .WithMany()
                        .HasForeignKey("CourseLevelLookupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StandardArticture.Models.Course", "Course")
                        .WithMany("MasterExams")
                        .HasForeignKey("CourseOid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseCategoryLookup");

                    b.Navigation("CourseLevelLookup");
                });

            modelBuilder.Entity("StandardArticture.Models.AppLookupHeader", b =>
                {
                    b.Navigation("LookupDetails");
                });

            modelBuilder.Entity("StandardArticture.Models.Course", b =>
                {
                    b.Navigation("MasterExams");
                });

            modelBuilder.Entity("StandardArticture.Models.CourseQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("StandardArticture.Models.CoursesMasterExam", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
